data:
  build: data/.
mysql:
  image: mysql
  env_file:
    - .env
  volumes:
    - ./sql:/sql
    - ./init:/docker-entrypoint-initdb.d
    - ./config:/etc/mysql/conf.d
  volumes_from:
    - data

mongo:
  image: mongo:3.0.2
  volumes_from:
    - data
  command: --smallfiles

web:
  build: web/.
  ports:
    - "80:8000"
  links:
    - mysql:db
    - mongo
  env_file:
    - .env